extends: kensho
rules:
  no-underscore-dangle: 0
  react/forbid-prop-types: 0
  react/no-access-state-in-setstate: 0
  react/no-deprecated: 0
  react/no-unused-prop-types: 0
  react/no-unused-state: 0
