extends: kensho
rules:
  no-nested-ternary: 0
  no-param-reassign: 0
  no-shadow: 0
  no-underscore-dangle: 0
  react/forbid-prop-types: 0
  react/no-access-state-in-setstate: 0
  react/no-deprecated: 0
  react/no-unused-prop-types: 0
  react/no-unused-state: 0
  react/sort-comp: 0
